# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16fAWkCVsveMgbBGnhzwT5kgnnRlHTYsX
"""

import streamlit as st
import pandas as pd
import numpy as np
import ee
import joblib
import folium
from groq import Groq

# =========================
# CONFIGURACIÓN GROQ API
# =========================
GROQ_API_KEY = st.secrets["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"]
client = Groq(api_key=GROQ_API_KEY)


# ==============================================================================
# CONFIGURACIÓN DE LA INTERFAZ DE USUARIO (STREAMLIT)
# ==============================================================================
st.set_page_config(
    page_title="Sistema Predictivo de Sequías - El Coyolar",
    page_icon="💧",
    layout="wide"
)

st.title("💧 Sistema de Alerta Temprana y Predicción de Riesgo Hídrico")
st.subheader("Monitoreo Satelital y Modelado IA para la Subcuenca Aportante de la Represa El Coyolar, Honduras")

# ==============================================================================
# CARGA DE COMPONENTES ESTÁTICOS (MODELO IA Y CARTOGRAFÍA OFICIAL)
# ==============================================================================
@st.cache_resource
def cargar_modelo_y_gee():
    # Inicializar la API de Google Earth Engine en el servidor web
    ee.Initialize()

    # Cargar el cerebro del Random Forest previamente guardado en Colab
    modelo = joblib.load("modelo_sequia_futuro.pkl")

    # Cargar la delimitación oficial de la cuenca desde HydroATLAS (Nivel 12)
    coleccion_cuencas = ee.FeatureCollection('WWF/HydroSHEDS/v1/Basins/hybas_12')
    punto_control_coyolar = ee.Geometry.Point([-87.5077, 14.3404])
    roi_subcuenca = coleccion_cuencas.filterBounds(punto_control_coyolar).geometry()

    return modelo, roi_subcuenca

try:
    modelo_rf, roi_subcuenca = cargar_modelo_y_gee()
    st.sidebar.success("🚀 Conexión con GEE y Modelo de IA cargados con éxito.")
except Exception as e:
    st.sidebar.error(f"❌ Error en la inicialización: {e}")
    st.stop()

# ==============================================================================
# PIPELINE EN TIEMPO REAL: EXTRACCIÓN SATELITAL DEL MES ACTUAL
# ==============================================================================
def remover_nubes_scl(img):
    scl = img.select('SCL')
    # CORRECCIÓN: Se cambian las llamadas .Or() por .or() compatibles con la API de GEE
    mask = scl.eq(4).orAnomalies(scl.eq(5)).orAnomalies(scl.eq(6)).orAnomalies(scl.eq(7)).orAnomalies(scl.eq(11))
    return img.updateMask(mask).clip(roi_subcuenca)

def obtener_datos_mes_actual():
    # CORRECCIÓN: Se usa pd.Timestamp de la librería pandas real
    fecha_hoy = ee.Date(pd.Timestamp.now().strftime('%Y-%m-%d'))
    fecha_inicio = fecha_hoy.advance(-1, 'month') # Evaluar las imágenes del último mes cerrado

    # 1. Ingesta de Sentinel-2 para el presente mes
    coleccion_s2 = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED') \
        .filterBounds(roi_subcuenca).filterDate(fecha_inicio, fecha_hoy).map(remover_nubes_scl)

    imagen_s2 = coleccion_s2.median()
    ndvi = imagen_s2.normalizedDifference(['B8', 'B4']).rename('NDVI')
    ndwi = imagen_s2.normalizedDifference(['B3', 'B8']).rename('NDWI')

    # 2. Ingesta de Landsat 8 para Temperatura Superficial (Celsius)
    imagen_l8 = ee.ImageCollection('LANDSAT/LC08/C02/T1_L2') \
        .filterBounds(roi_subcuenca).filterDate(fecha_inicio, fecha_hoy).median()
    lst = imagen_l8.select('ST_B10').multiply(0.00341802).subtract(273.15).rename('LST')

    # 3. Ingesta de Lluvia CHIRPS del mes actual
    lluvia_mes = ee.ImageCollection('UCSB-CHG/CHIRPS/DAILY') \
        .filterBounds(roi_subcuenca).filterDate(fecha_inicio, fecha_hoy).sum() \
        .reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_subcuenca, scale=5000).get('precipitation')

    # 4. Reducir espacialmente los mapas a promedios numéricos para la cuenca
    mapa_unificado = ee.Image.cat([ndvi, ndwi, lst])
    promedios = mapa_unificado.reduceRegion(reducer=ee.Reducer.mean(), geometry=roi_subcuenca, scale=30)

    # Retornar un DataFrame estructurado de una sola fila listo para la IA
    return pd.DataFrame([{
        'NDVI': promedios.get('NDVI').getInfo(),
        'NDWI_agua': stats.get('NDWI_agua').getInfo(),
        'NDWI_veg': stats.get('NDWI_veg').getInfo(),
        'LST': promedios.get('LST').getInfo(),
        'Lluvia_mm': lluvia_mes.getInfo()
    }])

# ==============================================================================
# FUNCIONES DE SOPORTE PARA CARTOGRAFÍA AUTOMÁTICA
# ==============================================================================
def obtener_subcuenca_automatica(lon, lat, nivel=12):
    nivel_str = str(nivel).zfill(2)
    cuencas = ee.FeatureCollection('WWF/HydroATLAS/v1/Basins/level' + nivel_str)
    punto = ee.Geometry.Point([lon, lat])
    cuenca = cuencas.filterBounds(punto).first()
    return cuenca.geometry()

def obtener_rio_automatico(roi, umbral_ocurrencia=50):
    gsw = ee.Image('JRC/GSW1_4/GlobalSurfaceWater')
    agua_permanente = gsw.select('occurrence').gt(umbral_ocurrencia).selfMask()

    vectores = agua_permanente.reduceToVectors(
        geometry=roi,
        scale=30,
        geometryType='polygon',
        eightConnected=True,
        maxPixels=1e9
    ).map(lambda f: f.set('area_m2', f.geometry().area()))

    return ee.Feature(vectores.sort('area_m2', False).first()).geometry()


# Ejecutar la extracción de datos al presionar el botón en la web
if st.sidebar.button("🔄 Actualizar e Interrogar Satélites"):
    with st.spinner("Analizando firmas espectrales en la subcuenca El Coyolar..."):
        try:
            df_actual = obtener_datos_mes_actual()

            # Calcular el SPI_3 en tiempo real basado en la lluvia del presente mes
            df_actual['SPI_3'] = (df_actual['Lluvia_mm'] - 85.4) / 42.1

            # Reordenar las columnas exactamente como las exige el Random Forest
            X_actual = df_actual[['NDVI', 'NDWI_agua', 'NDWI_veg', 'LST', 'SPI_3']]

            # ==================================================================
            # INFERENCIA PREDICTIVA A 30 DÍAS DE LA IA
            # ==================================================================
            prediccion_futura = modelo_rf.predict(X_actual)[0]
            probabilidades = modelo_rf.predict_proba(X_actual)[0]

            # Diccionario semántico de riesgos
            diccionario_riesgos = {
                0: {"nombre": "Riesgo Bajo (Sin Sequía)", "color": "green"},
                1: {"nombre": "Riesgo Leve", "color": "yellow"},
                2: {"nombre": "Riesgo Moderado", "color": "orange"},
                3: {"nombre": "Riesgo Severo (Alerta de Sequía)", "color": "red"}
            }
            resultado = diccionario_riesgos[prediccion_futura]

            # Mostrar los resultados en tarjetas métricas visuales
            col1, col2, col3, col4, col5 = st.columns(5)
            col1.metric("Vegetación (NDVI)", f"{df_actual['NDVI'].values[0]:.2f}")
            col2.metric("Agua Superficial (NDWI)", f"{df_actual['NDWI_agua'].values[0]:.2f}")
            col3.metric("Estrés Follaje (NDWI)", f"{df_actual['NDWI_veg'].values[0]:.2f}")
            col4.metric("Temperatura (LST)", f"{df_actual['LST'].values[0]:.1f} °C")
            col5.metric("Precipitación", f"{df_actual['Lluvia_mm'].values[0]:.1f} mm")

            # Mensaje grande con la predicción del próximo mes
            st.markdown(f"### 🔮 Predicción del Riesgo Hídrico para el PRÓXIMO MES:")
            if resultado["color"] == "green": st.info(resultado["nombre"])
            elif resultado["color"] == "red": st.error(resultado["nombre"])
            else: st.warning(resultado["nombre"])

            # ==================================================================
            # CORRECCIÓN: EL MAPA SE CORRE DESPUÉS DE OBTENER LA VARIABLE 'resultado'
            # ==================================================================
            st.markdown("### 🗺️ Cartografía Dinámica Inteligente Automatizada")
            st.write("Visualización espacial en tiempo real de la subcuenca y la red fluvial nativa extraída sin digitalización manual.")

            lon_coyolar, lat_coyolar = -87.50904715160283, 14.333509533380646

            # Extraer las geometrías directamente de la nube de Google
            geom_subcuenca = obtener_subcuenca_automatica(lon_coyolar, lat_coyolar)
            geom_rio = obtener_rio_automatico(geom_subcuenca)

            # Conversión de las geometrías de GEE a formatos GeoJSON
            geojson_subcuenca = geom_subcuenca.getInfo()
            geojson_rio = geom_rio.getInfo()

            # Inicialización del mapa Leaflet interactivo
            mapa_web = folium.Map(
                location=[lat_coyolar, lon_coyolar],
                zoom_start=13,
                tiles="OpenStreetMap",
                control_scale=True
            )

            # Capa 1: Dibujar la subcuenca con el color semáforo de la IA
            folium.GeoJson(
                data=geojson_subcuenca,
                style_function=lambda feature: {
                    'fillColor': resultado["color"],
                    'color': resultado["color"],
                    'weight': 2.5,
                    'fillOpacity': 0.35
                },
                tooltip=folium.Tooltip(f"<b>Subcuenca HydroATLAS</b><br>Alerta Predictiva a 30 días: {resultado['nombre']}")
            ).add_to(mapa_web)

            # Capa 2: Dibujar la red del cauce principal en azul fijo
            folium.GeoJson(
                data=geojson_rio,
                style_function=lambda feature: {
                    'fillColor': '#0033cc',
                    'color': '#0011aa',
                    'weight': 1.5,
                    'fillOpacity': 0.7
                },
                tooltip=folium.Tooltip("<b>Red Fluvial Principal (JRC Global Surface Water)</b>")
            ).add_to(mapa_web)

            # Desplegar el mapa en la web
            st_folium(mapa_web, width=1100, height=550)

        except Exception as error:
            st.error(f"Error durante el procesamiento del mes actual: {error}")
else:
    st.info("Presiona el botón de la barra lateral 'Actualizar e Interrogar Satélites' para calcular las variables del presente mes y predecir el estado hídrico del próximo periodo.")
